# Configuration for the API server.
apiServer:
  port: 8080
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicPort: 443
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  publicPort: 443
  publicScheme: https
